version: '3.9'

services:
  api:
    container_name: caffe-api
    image: caffe-api:v1.0
    build:
      context: .
      dockerfile: API/Dockerfile
    volumes:
      - Caffe-API:/app/API
      - ${HOME}/.aspnet/https:/https/
    networks:
      - Caffe-API
    ports:
      - "4000:80"
      - "4001:443"
    environment:
      - ASPNETCORE_URLS="https://+443;http://+80"
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password="Fckgwrhqq2!@#"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/caffeapi.pfx
    restart: always
    # env_file:
    #   - caffe-api.env
    # links:
    #   - caffe-sql-server
    #   - caffe-redis-server
    #   - caffe-postgresql-server
    #   - caffe-proxy

volumes:
  Caffe-API:
    external: false

networks:
  Caffe-API:
    driver: bridge
    external: false